### ISSUE TITLE
Get Google Maps key Working

### ISSUE THREAD

**Issue by joshuamorton** [gtagency/buzzmobile#1]
Add google maps key and keep it private so other people don't use it.

Also it currently exists in the git history, so we may want to go ahead and expunge it from history as well.

**Comment by irapha** [comment]
I already pushed changes to keep key private. Only things I need to do is expunge the key from the repo, correct?

**Comment by irapha** [comment]
I'm gonna have to temporarily disable continuous integrations so I can force overwrite the history to remove the keys

**Comment by casey2161** [comment]
This is y we don't include api keys in our repo children

**Comment by irapha** [comment]
Yes. Also, correction. I'm not removing continuous integration. I'm removing master branch protection. (!!!!!!!)

**Comment by diptodip** [comment]
rapha pls

**Comment by irapha** [comment]
friend this is not how you do.
after rewriting the history, you should have rebased, not merged.
