### ISSUE TITLE
Make max manual speed much smaller (not 1.0)

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#104]
Maybe have a rosparam for `max_speed`? If so, also needs to be used in wherever the auto speed is calculated (it's currently hardcoded as 1.0)

Set it to 0.1 or maybe even less.

**Comment by joshuamorton** [comment]
Putting it in writing: 1.0 may not (probably does not) mean 1.0 m/s, but instead 100% of maximal output.

**Comment by irapha** [comment]
Updated the issue to remove m/s
