### ISSUE TITLE
Make install script failsafe

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#126]
If it fails, it's hard to run it again after fixing the issue that made it fail the first time.

The issues seem to be the catkin_init and rosdep init. They fail if the've already been run.

**Comment by irapha** [comment]
as a note, cole said it seems to be failing when apt-get is run sometimes, because ubuntu might be running apt-get update in the background, which puts a lock in it.

possible solution, tho jank: https://askubuntu.com/questions/132059/how-to-make-a-package-manager-wait-if-another-instance-of-apt-is-running

**Comment by irapha** [comment]
To test this: create new VM, install buzzmobile, try running a launch file.

**Comment by joshuamorton** [comment]
Alternatively, use `wait` in the install script, this will block until all background processes are finished.

**Comment by irapha** [comment]
bash files are async???

**Comment by joshuamorton** [comment]
I'm gonna to with 'maybe', I don't actually think it should be in this case, but if that's the problem, this should be a fix. Unless you mean that the system is auto-updating, but I don't think that's a thing that happens.

**Comment by irapha** [comment]
Actually I do think it happens. From what we read while trying to fix this
issue, it seems ubuntu might start up apt-get update (or something else
that locks apt-get) at a random point and that can cause the issue we found.

**Comment by joshuamorton** [comment]
Gross, I didn't find that when I was looking around.

**Comment by irapha** [comment]
This is the main one we looked at, because the error is the same as what we got:

https://stackoverflow.com/questions/23610628/detecting-avoiding-multiple-apt-get-dpkg-installs

> It works great, except in the case where some system process kicks in and starts updating APT databases in the background.. Then it fails with dpkg: error: dpkg status database is locked by another process.

**Comment by joshuamorton** [comment]
Keep in mind that that fix requires apt-get installing the tool.

**Comment by irapha** [comment]
Sure, I wasn't suggesting we use the solution in this stackoverflow. I was just showing you that it's most likely that our issue came from a background apt-get process updating databases.

**Comment by coletaylor788** [comment]
As an update, I edited the install script to use a wrapper function for apt-get that waits for other apt-get processes to terminate. It appears to not fail due to apt-get anymore. However, the application still can't be run after preparing the environment this way. I will continue looking into it.

**Comment by joshuamorton** [comment]
What issue are you hitting after build (on a clean env I assume?)

**Comment by irapha** [comment]
Sg

**Comment by coletaylor788** [comment]
@joshuamorton I can't remember exactly (was about a week ago) but I believe they looked like python dependencies.

**Comment by coletaylor788** [comment]
I plan on taking another look in the next couple of days to get more information

**Comment by coletaylor788** [comment]
Here is a couple of lines from the error that I think summarizes it.

```
ImportError: Could not find Qt binding (looked for: 'pyqt', 'pyside'):

ImportError for 'pyqt': No module named 'sip'
ImportError for 'pyside': No module named 'PySide'
```

So it looks like it is looking for pyqt or pyside as the QT binding for RQT (used for mission control). pyqt has a dependency on sip which doesn't appear to be installed and pyside is also missing.

Do you know anything about this and do either of you care which binding is used? It looks like pyqt is the default binding which would probably be easier to fix.

**Comment by coletaylor788** [comment]
@iRapha @joshuamorton

**Comment by irapha** [comment]
Is rqt still failing to install? We might need to look up how to properly
install it. Maybe there's an rqt_core or something we need to be depending
on.

**Comment by coletaylor788** [comment]
Yes, the problem is with rqt. I can look further into how to get it installed but want to make sure our app isn't depending on PySide vs. PyQT. Is there one that needs to be used as the binding or is either fine?

**Comment by irapha** [comment]
I believe neither of those are being explicitly used by us.

**Comment by coletaylor788** [comment]
Okay, thanks. I will proceed with the easiest way to install rqt then

**Comment by coletaylor788** [comment]
As an update, the RQT problems only occur in the virtual environment. If you run it outside the virtual environment, the issue doesn't exist.

**Comment by irapha** [comment]
This probably means that whatever is installing rqt is doing so outside of the venv.

**Comment by coletaylor788** [comment]
As an update, I think the issue may be related to Python 2 vs. 3. If I enter a python3 shell outside of the virtualenv and enter: "from qt_gui.plugin import Plugin", it gives the same import error (Sip and PySide). Howerver, it works from within the python (2) shell.

**Comment by coletaylor788** [comment]
Additionally, the import line works in python2 in the virtualenv.

**Comment by coletaylor788** [comment]
@iRapha @joshuamorton Are we supposed to be using Python 2 or 3?

**Comment by irapha** [comment]
Python3. As soon as the install script is confirmed working, we'll all get new VMs and start using python3 only. So whatever is installing pyqt is installing it for py2, which is not what we want. Maybe it's like a flag we need to set for rosdep? Or maybe we need to depend on a different version of rqt so it knows we're using py3?

**Comment by coletaylor788** [comment]
Status update at end of night:

When run with python3, it says it is missing sip. After manually compiling and installing sip with python3 (pip can't install it), it said it was missing PyQt. I installed and compiled it from source as well which removed that error. Now the error is "basestring is not defined". basestring is something only defined in Python2. It starts with rqt_gui which calls a method in qt_gui which is in python2.7.

**Comment by irapha** [comment]
So there's a slight chance we are going to have to move things to python2 (which should only be a matter of changing install script, since all the code has been locally tested in py2 anyways). I'm deferring this to @joshuamorton pls dont abandon us pls

**Comment by joshuamorton** [comment]
Indeed, it should be mostly issues in the install script, everything else should be backwards compatible (also `yield from` isn't supported in 2.7).

**Comment by coletaylor788** [comment]
Just let me know when y'all decide which version we plan on using. If we go with python 2, I will update the script as it should be easy to get working. Otherwise, once it is decided, I can keep troubleshooting the issues with python 3. There seems to be incompatibilities with rqt and python 3 where fixing one issue is just revealing another.

**Comment by joshuamorton** [comment]
Do py2, it'll be easier.

I hate ros.

**Comment by coletaylor788** [comment]
Okay, I'll work on it when I get time.
