### ISSUE TITLE
Namespace things correctly

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#136]
Right now, some launch files namespace rosparams, some don't. Some namespace all of our nodes, some not all. We want to be consistent and:

> namespace whatever we created

This means changing every `Subscribe('some_msg')` to `Subscribe('/buzzmobile/some_msg')`

But keeping `Subscribe('fix')` because fix is a third party message

**Comment by joshuamorton** [comment]
semi-blocking #121 based on this.
