### ISSUE TITLE
Create and test joystick node

### ISSUE THREAD

**Issue by kpberry** [gtagency/buzzmobile#16]

**Comment by coletaylor788** [comment]
Need to revise the steering code to adjust it to the actual turning radius of the car. The joystick is too sensitive right now.

**Comment by coletaylor788** [comment]
Code is pushed to actuator branch. Now should have full support. @iRapha I define a constant MAX_TURNING_ANGLE in the file to be 30 degrees. 1) does that sound about right? 2) Would it be better to make a global header file where we can store all these global constants? That way it would be easier to change if the hardware changes.

**Comment by irapha** [comment]
The `max_steering_angle` is already defined globally in the `constants.yaml`. You can use it as a rosparam:

`rosparam load buzzmobile/buzzmobile/constants.yaml`

Then in rospy you do: `rospy.get_param('max_steering_angle')` and in roscpp you do something like:

``` cpp
float angle;
ros::param::get("max_steering_angle", angle);
```

As a note, currently, the value in `constants.yaml` is 1.0 rads. That is too large. I also think 0.52rad (30deg) is large. I think ~15 deg sounds more like reality, especially when you consider that this max angle is from the middle/forward angle of 0. So 15deg gives the wheels a range of 30deg to cover.

In either case, we have an open issue to measure the correct max angle #33

**Comment by coletaylor788** [comment]
Still need to switch to constants.yaml

**Comment by irapha** [comment]
Oh, right, sorry. Lmk when you have a PR for that.

**Comment by coletaylor788** [comment]
Closed by #93

**Comment by irapha** [comment]
Just a note that we also tested this :)
