### ISSUE TITLE
Format project as a python package as well as Ros Package

### ISSUE THREAD

**Issue by joshuamorton** [gtagency/buzzmobile#19]
Add `__init__.py` to `buzzmobile/buzzmobile/` and elswhere if necessary, setup `from buzzmobile import _______` throughout the project.

**Comment by irapha** [comment]
Whomever does this needs to make sure it works well in ROS, not just as python files, mainly bc ROS nodes are not run from the same dir as where the files are.

**Comment by irapha** [comment]
So we ended up doing this with rosparams, as seen in #26

**Comment by joshuamorton** [comment]
Close this then maybe, its not super important then.
