### ISSUE TITLE
Fix masses and inertials

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#196]
Current in the car urdf, I reverted the mass of the car parts to be very small. The reason being we weren't able to see the car moving in gazebo. However, the long term solution is to uncomment out the `<!-- mass / -->` tags and remove the small-mass ones. Then, we'd need to modify the `max_torque` in `sim_car_interface.cpp` and potentially the `<inertials />` in urdf.

**Comment by chsahit** [comment]
http://gazebosim.org/tutorials?tut=inertia
