### ISSUE TITLE
Consider porting to Kinetic

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#198]
No one knows what this would entail right now.

This will also not happen for a long time, until we've at least done a public demo.

**Comment by chsahit** [comment]
I'm closing this issue and opening another one which is just porting to kinetic. The camera driver things that were blocking us are no longer an issue as a few months ago libusb_camera got ported to kinetic.  Being on Indigo has made things harder for new members. Working on porting install  script now.
