### ISSUE TITLE
Create ROS unit tests

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#20]
http://wiki.ros.org/unittest

These will automatically be run by travis ci at every push.

**Comment by joshuamorton** [comment]
I also kinda want us to use pytest, but I'm not sure if it is compatible with ROS.

**Comment by irapha** [comment]
MVP for this is starting with a simple `pytest` that is run from travis.

**Comment by irapha** [comment]
Also use coveralls or something for testing coverage (eventually... this will not be anytime soon)

**Comment by irapha** [comment]
~~Use gazebo for things
http://gazebosim.org/tutorials?cat=guided_i&tut=guided_i1~~

e: this part is now being tracked here: #112
