### ISSUE TITLE
build broken bc of apt-get

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#201]
is failing to fetch ros repos for some reason. See discussion: https://github.com/gtagency/buzzmobile/commit/34d006afe8483439912d9c1c890cb39a16daf99a

**Comment by jgkamat** [comment]
I tried taking a stab at this for a bit, but I can't reproduce this particular error, I did need to make a few changes to make it work for me partially. I'll submit a PR in a bit and see what happens on your build.

One of the things that I did was switch to using the official ros docker image, which might help with this problem.

**Comment by irapha** [comment]
I forgot to close this, but it was fixed.
