### ISSUE TITLE
Create map of architecture

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#25]
Having a map of nodes and messages would be useful for future reference.

**Comment by irapha** [comment]
Done, available on the Agency's public drive:

https://docs.google.com/drawings/d/1Lryui91lSutyC1TQhDmWI3JqDfefNB9E9RoSaBPHhcE/edit?usp=sharing

**Comment by joshuamorton** [comment]
Convert to a .dot or .pdf and add to github?

**Comment by irapha** [comment]
Instead I added the image to the readme
