### ISSUE TITLE
Fix Hardware eStop

### ISSUE THREAD

**Issue by dacohen** [gtagency/buzzmobile#36]
The Arduino should know if the car is e-Stopped. Right now something is disconnected. Debug in conjunction with RJ if necessary.

**Comment by irapha** [comment]
See discussion in #46 as it relates to this issue

**Comment by irapha** [comment]
Daniel says that the wire just isnt well connected (which needs to be fixed), we're testing tonight to see if it works when we touch it a bit

**Comment by irapha** [comment]
It worked. I'm gonna close this issue and we reopen it if we encounter problems with estop later on
