### ISSUE TITLE
Prune repo of unused things

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#39]
Such as two of the `image_const` nodes (we only need one, and it should arguably live in `tools`).
Or even the `lane_detector`, which we are scraping for the future `road_detector` node aka agencynet

**Comment by joshuamorton** [comment]
Ehh, I agree with the first part of this (redundant stuff), but the whole point of buzzmobile was to potentially have various ways of doing things, and use it as a testbed for stuff.

**Comment by irapha** [comment]
I'd argue those can happen in branches but master should be cleaner

**Comment by joshuamorton** [comment]
Depends, there's value in being able to test multiple things at once,
though I guess if you're smart enough with git you can merge non-branches
into each other to get that effect. Worth weighing in mind in any case.
