### ISSUE TITLE
Properly fix battery

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#42]
It disconnected again today, and I'm worried I might not be connecting it properly, so I'd like to get someone else fix it.

**Comment by joshuamorton** [comment]
(do we need to buy electrical tape for this)

**Comment by irapha** [comment]
Yes, but it also involves screwing the ends of the cable together to the battery again. I thought I had done it properly with a shitty screwdriver but I guess I haven't..

**Comment by ebarnette** [comment]
I'm going to the shop tonight so I'll take it apart and re-heat shrink it.
