### ISSUE TITLE
Move nodes to different folders

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#47]
`buzzmobile/mission_control/route_mapper.py` -> `buzzmobile/route_mapper/route_mapper.py`

@coletaylor788 I want your opinion on this:
`buzzmobile/sense/controller.py` -> `buzzmobile/plan/controller.py` (or `process/`)
Mainly because `controller` outputs a `CarPose`, so it does the planning

**Comment by coletaylor788** [comment]
plan seems best to me. It isn't doing much processing.

**Comment by iRapha** [comment]
sg.

**Comment by irapha** [comment]
Update: I just realized that 
`buzzmobile/route_mapper/route_mapper.py` is already in it's correct place. So as soon as @coletaylor788 merges #31, with `buzzmobile/plan/controller.py`, we can close this issue.

**Comment by coletaylor788** [comment]
I moved controller.cpp to plan/controller/src/

**Comment by coletaylor788** [comment]
Closed by PR #31
