### ISSUE TITLE
Consider removing horn_node

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#48]
Currently, we have no horn. But with the assumption that we will get one (this is pending discussion):

Shouldn't `car_interface` also process `CarPose` for handling turning horn on and off? Why do we need a separate node and separate message simply to say "horn is on/off", when the `CarPose` will already encode this information? (and if it doesn't currently encode it, it should shouldn't it?)

**Comment by coletaylor788** [comment]
I agree, it seems unnecessary. It is just that car_horn was a node ported from buzzmobile_old. Not sure if there was some reason for breaking it out separately last time.

**Comment by irapha** [comment]
@coletaylor788 didn't you fix this also?

**Comment by coletaylor788** [comment]
Probably fixed but not tested

**Comment by irapha** [comment]
We'll we can't actually test the horn at all anytime soon because we won't have a physical horn (issue tracked in #66 ). I'll close this issue and whenever we get a horn I'll make a new issue to check implementation.
