### ISSUE TITLE
lidar_to_frame still OOMs

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#62]

**Comment by irapha** [comment]
actual issue that was happening was #72

**Comment by diptodip** [comment]
this is fixed now, right? should it be closed

**Comment by irapha** [comment]
Fixed but not merged

**Comment by joshuamorton** [comment]
Does the fix include "Closes #whatever" in the commit message? If not, can we amend?

**Comment by irapha** [comment]
The PR's desc has "Fixes #whatever"

**Comment by irapha** [comment]
Fixed in #71
