### ISSUE TITLE
Make deployment similar on all platforms

### ISSUE THREAD

**Issue by joshuamorton** [gtagency/buzzmobile#64]
Following some discussion in #61, it might be better if we factored out parts of the travis ci build script into a `install.sh`, so that 

```
git clone
./install.sh
```

would install system dependencies, run `setup.py`, install rosdeps, etc. and allow deployment to be done the same way across all systems.

**Comment by joshuamorton** [comment]
I've started on this, basic workflow will be
- run `install.sh`
  - runs `python3 -m venv buzzmobile`, creating a virtualenv
  - install tensorflow from wheel
  - install opencv from source
  - install the ros dependencies
  - run setup.py
    - install all the python dependencies
  - run `rosdep`
  - run tests?

Current biggest issue is getting OpenCV to work (efficiently), because it doesn't play well with Ros or python3 or virtualenvs on their own, and we're using all three.

**Comment by irapha** [comment]
Hm. travis is currently doing most of those, including opencv. For a fuller list of things `install.sh` should do, maybe you can look at `.travis.yml`?
