### ISSUE TITLE
Rename/relocate GPS interpolation node.

### ISSUE THREAD

**Issue by diptodip** [gtagency/buzzmobile#7]
Currently, in `buzzmobile/sense/gps` we have `bearing.py`, `interpolate.py`, `gps_mapper.py` and `maps.py` which should be moved to `buzzmobile/process/gps_mapper`.

**Comment by irapha** [comment]
Probably maybe blocked by #12

**Comment by joshuamorton** [comment]
bump, no longer blocked.

**Comment by irapha** [comment]
Also closed in #65
