### ISSUE TITLE
Make queue_size=1 everywhere

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#72]
Having `queue_size=0` make ros use an unlimited sized queue, which just explodes your computer's RAM 🙃. If you think you have a memory leak because you're going OOM, maybe you just have this issue.

@kpberry is curently fixing this on the `launch` branch. I'm mainly making this issue for future reference.

**Comment by irapha** [comment]
The PR fixed some of these, but not all. @kpberry is working on a fix for the rest in a new PR

**Comment by kpberry** [comment]
plz stay closed this time
