### ISSUE TITLE
Freeze dependencies

### ISSUE THREAD

**Issue by irapha** [gtagency/buzzmobile#89]
https://github.com/gtagency/buzzmobile/blob/master/buzzmobile/setup.py#L11

We want to freeze the requirements as such:

http://www.kennethreitz.org/essays/a-better-pip-workflow

The idea is that we depend on a specific release of each of our dependencies, not on the latest release. When those dependencies get updated, they won't break our code.

We'd ideally freeze all our deps, not just python's. But idk how to easily do that with ROS dependencies.

**Comment by joshuamorton** [comment]
I don't know that there is a way to do that for those deps, looking at how catkin manages deps.
